spring.config.import=optional:file:.env[.properties]
spring.application.name=Library
spring.datasource.url=jdbc:postgresql://${PGHOST}:5432/${PGDATABASE}?sslmode=${PGSSLMODE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}